package pl.kurs.bestiariusz.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.*;
import pl.kurs.bestiariusz.enums.Rarity;

import java.util.Objects;

/**
 * Entity represent element of armor
 * Contains name, descrpition, statistic, special buffs,
 * rarity({@link Rarity}),
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Armor {
    /**
     * ID generated by DataBase
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * Name of armor
     */
    public String name;
    /**
     * Short description about armor
     */
    public String description;
    /**
     * Rarity of armor definied by enum
     */
    public Rarity rarity;
    /**
     * Main statistic like HP, armor, resistance
     */
    public String statistic;
    /**
     * Special statistic depends on armor set or some enhancement
     */
    public String specialBuffs;

    public Armor(String name, String description, Rarity rarity, String statistic, String specialBuffs) {
        this.name = name;
        this.description = description;
        this.rarity = rarity;
        this.statistic = statistic;
        this.specialBuffs = specialBuffs;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Armor armor = (Armor) o;
        return Objects.equals(id, armor.id) && Objects.equals(name, armor.name) && Objects.equals(description, armor.description) && rarity == armor.rarity && Objects.equals(statistic, armor.statistic) && Objects.equals(specialBuffs, armor.specialBuffs);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, description, rarity, statistic, specialBuffs);
    }
}
