package pl.kurs.bestiariusz.models;

import jakarta.persistence.*;

import lombok.*;
import pl.kurs.bestiariusz.enums.Region;

import java.util.Objects;

/**
 * Entity represent monster
 * Contains local number, region({@link Region},
 * type, name, description, weakness, strengths, level, boss
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Monster {
    /**
     * ID generated by DataBase
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * Number of occurence specific monster in given region
     */
    private int localNumber;
    /**
     * Region where monster actually occurs
     */
    @Enumerated(EnumType.STRING)
    private Region region;
    /**
     * Type of monster
     */
    private String type;
    /**
     * Name of monster
     */
    private String name;
    /**
     * Short description about monster
     */
    private String description;
    /**
     * Weakness to which he is susceptible
     */
    private String weakness;
    /**
     * Strengths definied his resistance for special damage
     */
    private String strengths;
    /**
     * Actual level of monster
     */
    private String level;
    /**
     * Value defining whether he is a boss
     */
    private boolean boss;

    public Monster(int localNumber, Region region,
                   String type, String name, String
                           description, String weakness, String strengths, String level, boolean boss) {
        this.localNumber = localNumber;
        this.region = region;
        this.type = type;
        this.name = name;
        this.description = description;
        this.weakness = weakness;
        this.strengths = strengths;
        this.level = level;
        this.boss = boss;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Monster monster = (Monster) o;
        return localNumber == monster.localNumber && boss == monster.boss && Objects.equals(id, monster.id) && region == monster.region && Objects.equals(type, monster.type) && Objects.equals(name, monster.name) && Objects.equals(description, monster.description) && Objects.equals(weakness, monster.weakness) && Objects.equals(strengths, monster.strengths) && Objects.equals(level, monster.level);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, localNumber, region, type, name, description, weakness, strengths, level, boss);
    }
}
