package pl.kurs.bestiariusz.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.*;
import pl.kurs.bestiariusz.enums.Rarity;

import java.util.Objects;

/**
 * Entity represent weapon
 * Contains name, damage, description, statstic, special buffs,
 * rarity({@link Rarity})
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Weapon {
    /**
     * ID generated by DataBase
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    public String name;
    /**
     * Value defining actual power of weapon
     */
    public int damage;
    /**
     * Short description about weapon
     */
    public String description;
    /**
     * Rarity of weapon definied by enum
     */
    public Rarity rarity;
    /**
     * Main statistic like damage
     */
    public String statistic;
    /**
     * Special statistic depends weapon on  or enhancement
     */
    public String specialBuffs;

    public Weapon(String name, int damage, String description, Rarity rarity, String statistic, String specialBuffs) {
        this.name = name;
        this.damage = damage;
        this.description = description;
        this.rarity = rarity;
        this.statistic = statistic;
        this.specialBuffs = specialBuffs;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Weapon weapon = (Weapon) o;
        return damage == weapon.damage && Objects.equals(id, weapon.id) && Objects.equals(name, weapon.name) && Objects.equals(description, weapon.description) && rarity == weapon.rarity && Objects.equals(statistic, weapon.statistic) && Objects.equals(specialBuffs, weapon.specialBuffs);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, damage, description, rarity, statistic, specialBuffs);
    }
}
