package pl.kurs.bestiariusz.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.*;
import pl.kurs.bestiariusz.enums.Rarity;

/**
 * Entity represent element of armor
 * Contains name, descrpition, statistic, special buffs,
 * rarity({@link Rarity}),
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Armor {
    /**
     * ID generated by DataBase
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * Name of armor
     */
    public String name;
    /**
     * Short description about armor
     */
    public String description;
    /**
     * Rarity of armor definied by enum
     */
    public Rarity rarity;
    /**
     * Main statistic like HP, armor, resistance
     */
    public String statistic;
    /**
     * Special statistic depends on armor set or some enhancement
     */
    public String specialBuffs;

    public Armor(String name, String description, Rarity rarity, String statistic, String specialBuffs) {
        this.name = name;
        this.description = description;
        this.rarity = rarity;
        this.statistic = statistic;
        this.specialBuffs = specialBuffs;
    }
}
