# --- DataBase ---
spring.datasource.url=jdbc:mysql://localhost:3306/Bestiariusz?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# --- JPA ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# --- Server ---
server.port=8080